-- 1. FIX SUBJECTS TABLE (Fixes 400 Bad Request)
CREATE TABLE IF NOT EXISTS subjects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL, -- 'Junior' or 'Senior'
  department TEXT NOT NULL, -- 'General', 'Science', 'Arts', 'Commercial'
  teacher TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for subjects
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;

-- Allow everything for now (CRUD) so Admin can work freely
DROP POLICY IF EXISTS "Public full access subjects" ON subjects;
CREATE POLICY "Public full access subjects" ON subjects FOR ALL USING (true) WITH CHECK (true);


-- 2. FIX NOTICES TABLE (Fixes 401 Unauthorized)
CREATE TABLE IF NOT EXISTS notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  audience TEXT NOT NULL, -- 'Student', 'Staff', 'All', 'Public'
  show_on_ticker BOOLEAN DEFAULT false,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for notices
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;

-- CRITICAL: Allow Public Read Access (for Landing Page Ticker)
DROP POLICY IF EXISTS "Public read notices" ON notices;
CREATE POLICY "Public read notices" ON notices FOR SELECT USING (true);

-- Allow Authenticated (Admin/Staff) to Insert/Update/Delete
DROP POLICY IF EXISTS "Authenticated full access notices" ON notices;
CREATE POLICY "Authenticated full access notices" ON notices FOR ALL USING (true) WITH CHECK (true);


-- 3. FIX CLASSES TABLE (Just in case)
CREATE TABLE IF NOT EXISTS classes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  level TEXT NOT NULL,
  form_teacher TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public full access classes" ON classes;
CREATE POLICY "Public full access classes" ON classes FOR ALL USING (true) WITH CHECK (true);
