-- Create Timetables Table
CREATE TABLE IF NOT EXISTS public.timetables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT REFERENCES public.classes(id) ON DELETE CASCADE,
    day TEXT NOT NULL, -- Monday, Tuesday...
    subject TEXT NOT NULL,
    teacher TEXT,
    start_time TEXT NOT NULL, -- "08:00"
    end_time TEXT NOT NULL, -- "09:00"
    room TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.timetables ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.timetables
    FOR SELECT USING (true);

CREATE POLICY "Enable insert/update for staff/admin" ON public.timetables
    FOR ALL USING (
        auth.uid() IN (SELECT id FROM public.staff) OR 
        auth.uid() IN (SELECT id FROM public.admin_profiles)
    );

-- Insert Sample Data for JSS 2 (Assuming 'JSS 2' exists, else we rely on ID logic or matching name)
-- First, identifying a class ID for JSS 2 to attach data to. 
-- We'll use a DO block to find the class or fallback.

DO $$
DECLARE
    target_class_id BIGINT;
BEGIN
    -- Check for JSS 2 class
    SELECT id INTO target_class_id FROM public.classes WHERE name = 'JSS 2' LIMIT 1;
    
    -- If not found, check JSS 1, else just pick the first class found
    IF target_class_id IS NULL THEN
        SELECT id INTO target_class_id FROM public.classes WHERE name = 'JSS 1' LIMIT 1;
    END IF;
    
    IF target_class_id IS NULL THEN
        SELECT id INTO target_class_id FROM public.classes LIMIT 1;
    END IF;

    -- Delete existing entries for this class to avoid duplicates on multiple runs
    DELETE FROM public.timetables WHERE class_id = target_class_id;

    -- Insert Sample Schedule
    IF target_class_id IS NOT NULL THEN
        INSERT INTO public.timetables (class_id, day, subject, teacher, start_time, end_time, room)
        VALUES 
            (target_class_id, 'Monday', 'Mathematics', 'Mr. Ibrahim', '08:00 AM', '09:00 AM', 'Class A'),
            (target_class_id, 'Monday', 'English', 'Mrs. Amina', '09:00 AM', '10:00 AM', 'Class A'),
            (target_class_id, 'Monday', 'Break', '', '10:00 AM', '10:30 AM', ''),
            (target_class_id, 'Monday', 'Basic Science', 'Mr. Okon', '10:30 AM', '11:30 AM', 'Lab 1'),
            
            (target_class_id, 'Tuesday', 'P.H.E', 'Coach', '08:00 AM', '09:00 AM', 'Field'),
            (target_class_id, 'Tuesday', 'Civic Education', 'Mrs. Kuti', '09:00 AM', '10:00 AM', 'Class A'),

            (target_class_id, 'Wednesday', 'Mathematics', 'Mr. Ibrahim', '08:00 AM', '09:00 AM', 'Class A'),
            (target_class_id, 'Wednesday', 'Islamic Studies', 'Ustadh Ali', '12:00 PM', '01:00 PM', 'Mosque');
    END IF;
END $$;
